- scripts/build.js
- scripts/create-package.js
- scripts/install-dependencies.js
- scripts/utils.js
`npm` and `npx` have to be spawned as `npm.cmd` and `npx.cmd`; We could use cross-spawn, but we want to avoid dependencies in install-dependencies.
> Make build scripts work on Windows

- scripts/create-package.js
create-package.js has the start of code to create a "fat" VSIX package that could potentially work on all supported platforms.
This is preliminary work and we don't even ship a npm script to generate that kind of package right now.
It also doesn't even really function, because sqlite3 uses the bindings module to find its own module and the bindings module mostly just looks in paths that don't encode the platform name. This means the bindings module doesn't really let us ship more than one set of platform specific sqlite3 files.
There is an exception: the bindings module will look in directories of the form:
lib/bindings/node-v$node_modules_abi-$platform
This would work except the node modules ABI changes fairly frequently and may be different at build time and run time.
create-package.js …
> build: Don't duplicate sqlite3 modules in package

- scripts/build.js
Extend the transform code to transform strings within core/control-plane:
* The EXTENSION_NAME constant
* Some other identifiers
* URLS to continue.dev and SaaS providers (changed to example.com)
The EXTENSION_NAME transform is needed to get config settings working properly, since we lookup configuration settings under EXTENSION_NAME.<setting>.
***NOTE***: This includes the last commit in #53 - it will need rebasing after that is merged.
> Transform EXTENSION_NAME and control plane info

- package.json
- scripts/create-package.js
I've hit a few more problems testing packaging:
1. We're shipping intel mac packages that don't work for a variety of reasons and couldn't work given how old the hardware is
2. We're not copying sqlite3 right
3. create-package.js expects command line arguments to occur in a prescribed order (yuck!)
> More packaging fixes

- scripts/create-package.js
This fixes a problem where start_ollama.sh wasn't packaged (it was the only place where we globbed on platform.)
> scripts/build.js: Fix backwards arguments to minimatch

- scripts/create-package.js
fs.promises.access() rejects the promise with an Error instead of return false if the file doesn't exist.
> create-package.js: Use fs.promises.access() correctly

- package-lock.json
- scripts/build.js
The recent de-dashification of granite-code to granitecode was incomplete and broke the extension. This pull request addresses that.
> Hopes are dashed

- .vscodeignore
- README.marketplace.md
- README.md
- package-lock.json
- package.json
- scripts/create-package.js
Our README.md is project focused, not extension focused and not suitable for displaying on the VSCode extension marketplace. Add a separate README file to use for the marketplace and point to it with --readme-path.
This required updating vsce a newer version; it is unclear why we were using an old version.
This also adjusts displayName and description to be shorter and more to the point.
> Add a marketplace specific README, tweak metadata

- .github/workflows/publish.yaml
The publishing logic depends on tags being in the cloned repository to know which pre-release version to assign to the output package.
Unfortunately, GitHub by default does a shallow clone with no branches or tags.
This commit adds `fetch-tags: true` to ensure the tags are fetched at clone time.
Suggestion by Owen Taylor.
> ci: Fetch tags when cloning repo

- .github/workflows/publish.yaml
The publishing logic depends on tags being in the cloned repository to know which pre-release version to assign to the output package.
Unfortunately, GitHub by default does a shallow clone with no branches or tags.
commit eb7855c52297e43fd25167c1859abd7fd4824d39 attempted to fix this issuing by using `fetch-tags: true` in the workflow yaml, but unfortunately that feature is currently broken:
https://github.com/actions/checkout/issues/1471
This commit instead, switches to using
fetch-depth: 0
to tell git not to do a shallow clone, and fetch tags.
To keep things performant it also adds:
filter: blob:none
to make files get fetched at git checkout time on deman instead of git clone time.
> ci: Perform blobless clone instead of shallow clone

- scripts/install-dependencies.js
The install-dependencies script installs in-tree node modules for testing Granite.Code directly in a VS Code environment.
It does this by putting the modules in build/ and node_modules/ of the repository root. This is distinct from where dependencies used for creating the installable VSIX package which go in package-dependencies/
commit 66c083e8e5ddbba43ae3fb18ec48a3c6bccd09dd makes install-dependencies a little smarter about what to do when there are no per-arch substitutions in the install source or destination.
It allowed us to drop platforms lines of the form:
platforms: [`${process.platform}-${process.arch}`],
which were just used to force the script to only perform an install of the specified source once, instead of once per arch.
The in-tree node modules also had platforms lines of …
> install-dependencies: Install correct in-tree modules

- scripts/create-package.js
create-package has a function expandPackageConfigurationEntry that takes a configuration entry (used for defining what gets packaged), and expands it include all platforms that are getting put in the package.
As a last ditch fallback, if it could find no platform to put in the package, it would just use the original, unexpanded entry.
This fallback is wrong, because it will trigger for platforms that are supposed to be filtered out when --target is used.
It's unnecessary when --target isn't used because there should be no fallback in that case (unless an unsupported platform was specified in the configuration, but that's not allowed anyway).
Likely, the fallback is a vestigial remanant of when the function was written a different way.
This commit drops it.
> create-package: Don't ship off-target ONNX files

- README.md
There's inexplicably a capital C after the comma in that sentence that points users to the upstream continue.dev GitHub repository.
This commit drops the comma.
> README.md: Fix typo after upstream link

- .github/workflows/publish.yaml
Deploy pre-releases to https://open-vsx.org/, as part of the publish-packages CI job
Fixes #90
> ci: deploy pre-releases to Open VSX

- .github/workflows/publish.yaml
commit 01d0c2d448d2f6f502f2f685ad7e8031848f143a introduced a stray indentation problem that is making the workflow fail.
This commit should fix things.
> ci: Fix indentation error in yaml

- .github/workflows/publish.yaml
The OpenVSX registry publishing step has a copy and paste error, so it says "VSCode Marketplace" instead of "OpenVSX Registry".
This commit fixes that.
> ci: Fix working for OpenVSX registry publishing step

- .vscode/tasks.json
- package.json
- scripts/build.js
- scripts/create-package.js
- scripts/install-dependencies.js
- scripts/update-package-json.js
Updates to latest granite/integration
* Upstream UI changes to chat UI
* Granite.Code configuration switched over to config.yaml from config.json
* New logging console (needs to be enabled in settings)
Changes from the Granite.Code team (upstream and not)
Jazzcort (5):
restore jazzcort's contextLength fix
Fixed bug for pruning beyond last 5 messages
Erased the extra condition
Improved efficiency of one-third-pruning
Forbid file mentioning for large files
Keerthana Panyam (2):
rejected edit trims the trailing whitespaces
remove redundant code
Fred Bricon (5):
Fix Chat mode cycling on VS Code
Disable Granite.Code when launching in Dev mode
Enable tools support for Cogito on Ollama
Mitigate registerCopyBufferSpy failures
Fix 'undefined' this on files/changed listener
Owen W. Taylor:
Reliably …
> Update to latest granite/integration

- .github/workflows/publish.yaml
Just building the config-yaml package from the vscode tasks isn't sufficient.
Possibly it would be better if `npm run build` did this itself. That would require making the vscode tasks run in parallel - first run 'npm run build', *then* start vite.
But I think even better would be if upstream was fixed so that this package was fed as typescript source to the build process, and not separately compiled to JS.
> workflows/publish.yaml: Also build config-yaml here

- scripts/build.js
According to @owtaylor 's suggestion, here we add the negative lookahead in the regex so we can add `no-transform` in the comment that is right after the string literal to avoid transform.
Details: https://github.com/Granite-Code/continue-for-granite/pull/39#issuecomment-2876933247
> Add negative lookahead to avoid some transforms

- extension.ts
Otherwise, it leads to:
```
Cannot find name 'vcode'. Did you mean 'vscode'? ts(2552) [Ln 30,
Col 11]
```
Fallout from b17613ccee72d768dc9836d94541a6794b0222ed
> extension.ts: Fix typo
